### ISSUE TITLE
link out to Orphanet from Protege currently goes to a 404 page

### ISSUE THREAD

**Issue by nicolevasilevsky** [protegeproject/protege#1192]
@gouttegd 
In Mondo, the link outs from Orphanet IDs are now going to a 404 page (see example: Orphanet:79240 redirects to https://www.orpha.net/consor/www/cgi-bin/OC_Exp.php?Expert=79240). I'm guessing something changed on the Orphanet website. 

Thank you for looking into this!

cc @sabrinatoro @twhetzel

**Comment by gouttegd** [comment]
What seems to have changed is that they moved their `cgi-bin` directory one directory upward, so the expected URLs should now be `https://www.orpha.net/consor/cgi-bin/OC_Exp.php?Expert=79240` instead of `https://www.orpha.net/consor/www/cgi-bin/OC_Exp.php?Expert=79240` (note the missing `www/` in the first URL).

**Comment by nicolevasilevsky** [comment]
thanks for your quick reply @gouttegd! Do we have to wait for the next Protege release to see this fix?

**Comment by gouttegd** [comment]
Yes, sorry. It’s a code change, not something that can updated on the fly on an existing Protégé installation.

**Comment by nicolevasilevsky** [comment]
All good @gouttegd! I'm super grateful for you and your contributions to Protege. 💟
