### ISSUE TITLE
Beta 17 on Yosemite spins for 15 seconds before loading ontology w/Open 

### ISSUE THREAD

**Issue by FrankC01** [protegeproject/protege#187]
Has a simple ontology built with earlier beta version. Updated to 17 today and now, when opening a previous ontology, takes a good 15 seconds during which beach ball spins.

**Comment by matthewhorridge** [comment]
Does this happen after you have selected the ontology for opening?  Also, is the ontology contained in a directory with a lot of other files and folders?

**Comment by FrankC01** [comment]
I start Protege, it opens with a blank ontology
I select Open which pops up the finder dialog, navigate to my user home folder and select the file to load.

Spin, wait, spin, wait..wait...

The file exists in a folder with about 20 other folders and files.

**Comment by matthewhorridge** [comment]
Hi Frank,

Thanks for the extra details.  I suspect Protege is searching through the files and folders to index them for imports (even if there aren't any).  You will be able to confirm this by moving the ontology that you want to load to a folder with no other files or folders in it and then opening it from there.

There is some discussion on this issue here:

https://github.com/protegeproject/protege/issues/83

**Comment by FrankC01** [comment]
Matthew:

Three tests:

1. As is: Open test ontology via "Open Recent" or "Open..". Results in wait times ~ 30 seconds

2. Mod catalog config: In "catalog-v001.xml"  change "recursive=true" to "recursive=false", open via "Open...". Results in immediate open of ontology.

3. Simple Folder: Moved files as you directed, change back to "recursive=true", open via "Open...". Results in immediate open of ontology.

I am going to continue with the beta using option #3 for time being.

Thanks for the reference!

**Comment by matthewhorridge** [comment]
Frank, thanks for the feedback and testing.  Much appreciated.

**Comment by matthewhorridge** [comment]
I'm closing this issue and referencing it from #83, which is now the canonical issue for this.
