### ISSUE TITLE
Fact++ plugin: not in Protégé 5, cannot write to plugins folder

### ISSUE THREAD

**Issue by uscholdm** [protegeproject/protege#204]
I just downloaded Protégé 5 beta 17. I was surprised to see Fact++ not already installed. I tried to download the file to the plugins folder, per usual, but was not able to write  the uk.ac.manchester.cs.owl.factplusplus-P4.3-v1.6.3.jar file to that folder. I normally have admin privilieges for my laptop, so this is odd.

It is also not listed here: http://protegewiki.stanford.edu/wiki/Inference 

I see a number of issues on Fact++ (e.g. #97) , but I did not notice one explaining this.  What changed? Is this plugin becoming obsolete?

Thanks

**Comment by uscholdm** [comment]
I since tried using the File > Check for Plugins command, and got it to load successfully. This issue can be closed.

**Comment by csnyulas** [comment]
Just a note on the wiki entry:
Fact++ has a wiki page here, http://protegewiki.stanford.edu/wiki/Pr4_UG_rp_Reas_FaCT%2B%2B , which is part of the "Protege 4 User Guide" pages. We should probably create a proper plugin page for it on our wiki, and declare it Category:Reasoner, so that it gets listed appropriately.
