### ISSUE TITLE
The list in the "Ontology sources changed" window is not visible.

### ISSUE THREAD

**Issue by uscholdm** [protegeproject/protege#207]
This just started with Protégé 5 Beta 17, previously I was using 4.3.  

When ontologies change outside of Protégé, it very nicely lets you know and gives a list of changed ontologies. That list is not visible any more and there is a lot of unnecessary whitespace, which is likely related. To see the files, I have to resize the window.  See image.

![image](https://cloud.githubusercontent.com/assets/10777545/7150224/cdbac71a-e2cc-11e4-96f9-20482646d741.png)

**Comment by csnyulas** [comment]
I wonder what ontology/ontologies have you changed outside Protege that you got this window. 
When I change ontolgy files outside of Protege and switch back to Protege I get an "Ontology sources changed" window, but that does not try to show a list of ontologies, but only one ontology edited in the current window, with the following text
"An ontology has changed outside of Protege.

<ontology name>

Would you like to reload?"

plus a warning message, if I had local changes in Protege in the meantime. This message is rendered properly in my case.

**Comment by csnyulas** [comment]
You can ignore my previous comment, since I was able to get to the "Ontology sources changed" window that shows a list of ontologies changed externally, namely in the case when we have ontology imports and more than one ontologies from the import closure changes.
However, in my tests the table always rendered properly on Ubuntu and most of the time in Windows 7. The only time that the content of the window did not render properly in Win 7 was the very first time the I received this notification. In that occasion, the table was rendered  properly for a second, then it was resized, while apparently the preferred/actual size of the container has been forgotten, resulting in a similarly view that you reported. After manually modifying the alert window, the change ontologies table got rendered properly, and I could not reproduce the faulty behavior again.

@uscholdm Can you reliably reproduce this behavior? If yes, could you please describe your setup and steps that you use to reproduce it?

**Comment by matthewhorridge** [comment]
This seems to depend on the size of the dialog.  If I resize the dialog I can get it to collapse as shown above.  Resizing further makes it fill the whole window.

**Comment by matthewhorridge** [comment]
I think the layout issues are due to something funky with ```TableUtils```

**Comment by uscholdm** [comment]
It happens every time for me. I am using WIndows 8.1, 64bit OS. Do you need any other setup details?
When I change multiple ontologies outside of protégé, they do not show up, as indicated in my first image. I have to resize the window. If I only have one ontology, the layout is different, and I can see it fine.

**Comment by matthewhorridge** [comment]
Yeah, it's no an OS thing.  I can reproduce it and now I'm just figuring out the best way of fixing it.  Thanks for all of the details so far.

**Comment by matthewhorridge** [comment]
This was fixed at some point.  Working in 5.0.0 RC1.
