### ISSUE TITLE
How does one create property chains in Protege 5?

### ISSUE THREAD

**Issue by ivanfilippenko** [protegeproject/protege#217]
That's basically the short question.  I see various references to a useful-looking property chaining capability in Protege 4, but in Protege 5, the only thing that suggests itself is "SuperProperty Of (Chain)", which, however, seems merely to provide an awkward type-in interface for what ultimately amounts to asserting that a property is a SubProperty Of another (for which there's already a separate, more convenient interface).  What is the real meaning and purpose of "SuperProperty Of (Chain)"?

I'd really like to create property chains of the sort that I find in Protege 4 based tutorials and discussions.

**Comment by csnyulas** [comment]
This is not an appropriate issue for our issue tracker. If you have a question about how to do something, you should write to our mailing list and we will try to help you there.
You can subscribe to our mailing list here:
http://protege.stanford.edu/support.php
or here:
https://mailman.stanford.edu/mailman/listinfo/protege-user

**Comment by ivanfilippenko** [comment]
Hi, thanks for pointing that out.  As in the case of another question, I subsequently posted this question (on April 26) to the Protege User project on Nabble (http://protege-project.136.n4.nabble.com/), but it keeps showing "This post has NOT been accepted by the mailing list yet." which must explain the lack of replies.  Could you please ensure that my question is accepted?  Thank you very much!  -- Ivan

**Comment by csnyulas** [comment]
I observed that in the meantime you have subscribed to the protege-user mailing list, and you were able tp send email directly to the mailing list address, where your questions have been answered (or are in the process to be answered by our colleagues and the community).

I have just added you to the "members" user group on nabble, so that in the future you should be able to post to our mailing list also through the nabble interface.

**Comment by ivanfilippenko** [comment]
Thank you!  -- Ivan
