### ISSUE TITLE
Chinese does not display correctly without changing the font

### ISSUE THREAD

**Issue by matthewhorridge** [protegeproject/protege#234]
Another problem is that the new version of peotege displays Chinese in boxes, but when I changed the font to "SimSun" which supports Chinese by using 4.0, the problem gone. So I recommend that the new version should add font change support again.  (from #229)

**Comment by matthewhorridge** [comment]
Closing this because it seems to be a Java setup issue.

**Comment by Erickrus** [comment]
Reason: JRE along with Protege doesnt support Unicode well.
So: Try to use system jre/jdk instead (Because there're some fonts configuration while installing JDK on your system).
HOW-TO-DO: Edit run.bat file, replace jre/bin/java to java. In my case, it resolve.
Hopefully, other people could benefit.
