### ISSUE TITLE
where can I set font

### ISSUE THREAD

**Issue by Emma123456** [protegeproject/protege#245]
I want to set font to Microsoft Himalaya font ,because I want to build Ontology using tibet .but I don't know how to do that

**Comment by stdotjohn** [comment]
On 09/10/2015 09:15 AM, Emma123456 wrote:
>
> I want to set font to Microsoft Himalaya font ,because I want to build 
> Ontology using tibet .but I don't know how to do that
>

My suspicion is that this is a misdiagnosis.  It would be better to have 
a description of what isn't working together with, if you have one, an 
ontology.

There are two things that need to work in order to use tibetan 
characters in Protege.

First you need to be able to enter the characters.  This is an operating 
system issue not a Protege issue.  One thing that is useful here - I am 
not multilingual so I don't know how well this works in all languages - 
is to setup your keyboard to work with the language that you desire.  I 
have at one point done this in Linux (here this feature is called 
setting the keyboard layout), OS X and Windows.

Protege will then store these characters in Unicode and will write them 
out using the UTF-8 encoding.

Second - and when I was working on this I never completely understood 
this part - once the characters are entered it is nice if you can see 
them.  Usually this just works but on some machines the characters just 
come out as boxes.  Is this the problem that you are having?  If so I 
think that there is or was a different bug tracker for that item.

I suspect that this simply worked when I tried tibetan on my machine.  
While I do not know the characters, I believe that these are tibetan:



One last thing.  I believe that it is best practice to put the language 
specific strings in an rdfs:label if you want a multilingual ontology.  
This way you can provide several different language variants for the 
same item.


-Timothy

**Comment by Emma123456** [comment]
Thanks for your reply.This is my envirement.
Starting Protege Desktop (Version 5.0.0, Build = beta-15)
Platform:
    Java: JVM 1.7.0_75-b13 Memory: 1882M
    Language: zh, Country: CN
    Framework: Apache Software Foundation (1.5)
    OS: windows7 (6.1)
    Processor: x86-64
Plugin: Cajun Visualization Library (1.0.2)
Plugin: Guava: Google Core Libraries for Java (17.0.0)
Plugin: DL Query (2.0.2)
Plugin: OWLViz (4.1.4)
Plugin: OWL Code Generation Plug-in (1.0.2)
Plugin: OWL Difference (4.1.1)
Plugin: Protege Editor OWL (5.0.0.beta-15)
Plugin: Protege SPARQL Plugin (1.0.0)
Plugin: Explanation Workbench (1.0.0)
Plugin: Protege HermiT Integration (1.0.0)
Plugin: OntoGraf (1.0.3)
Plugin: OWL Difference Engine (1.0.1)
Plugin: OWLAPI RDF Library (1.0.2)
Plugin: OWLAPI Distribution (3.5.0)
        Cajun Visualization Library Plugin has no plugin.xml resource
        Guava: Google Core Libraries for Java Plugin has no plugin.xml resource
        OWL Difference Engine Plugin has no plugin.xml resource
        OWLAPI RDF Library Plugin has no plugin.xml resource
        OWLAPI Distribution Plugin has no plugin.xml resource
   
The problem is that Chinese character is ok and Tibet character  is box showing on protege UI . I can able to  enter tibet characters On my operator system. When I save file as RDF/XML and get XML file,all  characters are fine.
![qq 20150912160932](https://cloud.githubusercontent.com/assets/14220928/9830665/c92b50de-5969-11e5-83d5-8a5f54604996.png)

**Comment by Emma123456** [comment]
@stdotjohn  Thanks for your help. I fix the problem.I put himalaya.ttf to $JAVA_HOME/jre/lib/fonts/fallback. I am sorry that I think it's a bug.Thanks very mutch again.

**Comment by Erickrus** [comment]
Reason: JRE along with Protege doesnt support Unicode well.
So: Try to use system jre/jdk instead (Because there're some fonts configuration while installing JDK on your system). 
HOW-TO-DO: Edit run.bat file, replace jre/bin/java to java. In my case, it resolve.
Hopefully, other people could benefit.
