### ISSUE TITLE
Add an option to disable drag and drop in hierarchies

### ISSUE THREAD

**Issue by matthewhorridge** [protegeproject/protege#347]

**Comment by bdionne** [comment]
This works well. 

I'm wondering if an alternative approach would be to add support to `OWLModelManagerTree` for disabling drag/drop. That way subclasses could disable it without disabling it everywhere else. I know NCI wants it disabled in the navigation pane of `EditTab` but certain power users are going to be allowed to use the other tabs like the classes tab and we could leave it enabled there. @fragosog may have an opinion on this.

**Comment by matthewhorridge** [comment]
Re-opening as the requirement is that drag should be possible but drop should not be possible

**Comment by bdionne** [comment]
thanks @matthewhorridge - this works ok, but there is an edge case that fails. Drag/Drop within the classes tree sometimes acts like a copy rather than a move. Debugging it reveals that the remove axiom[1] fails. Try moving EpithellialCell in this[2] small example.


[1]: https://github.com/owlcs/owlapi/blob/version4/impl/src/main/java/uk/ac/manchester/cs/owl/owlapi/Internals.java#L678
[2]: https://github.com/bdionne/nci-edit-tab/blob/master/samples/owl2-test-cases-Defined-Annotated.owl

**Comment by matthewhorridge** [comment]
Ah, I see what the problem is.  EpithelialCell has axiom annotations.  When the remove takes place it tries to remove the axiom without annotations and this axiom doesn't exist in the ontology, so the remove fails.

I'm going to open a new issue for this.
