### ISSUE TITLE
InferredOWLClassHierarchyProvider can crash depending on the reasoner implementation

### ISSUE THREAD

**Issue by bdionne** [protegeproject/protege#403]
[InferredOWLClassHierarchyProvider](https://github.com/protegeproject/protege/blob/master/protege-editor-owl/src/main/java/org/protege/editor/owl/model/hierarchy/cls/InferredOWLClassHierarchyProvider.java#L172) crashes if the reasoner [returns](https://gist.github.com/bdionne/273eb26f60d5e6d4916624800cb78ed3)  an immutable collection. Using `getEntitiesMinus` seems to fix it.

**Comment by bdionne** [comment]
Thanks @matthewhorridge - is [this one](https://github.com/protegeproject/protege/blob/61c4f7b63a29dfd5f11c39017375f35ae301f3bb/protege-editor-owl/src/main/java/org/protege/editor/owl/model/hierarchy/cls/InferredOWLClassHierarchyProvider.java#L138) ok?

**Comment by andrewdbate** [comment]
Sorry to be commenting on a closed issue... but I'm currently getting this exact crash due to a reasoner returning an immutable collection.

The code immediately below calls remove: https://github.com/protegeproject/protege/blob/6eb72cbf1244a25bc2b8fc0a672047a4d55a81c4/protege-editor-owl/src/main/java/org/protege/editor/owl/model/hierarchy/cls/InferredOWLClassHierarchyProvider.java#L94-L100

The problem seems to be that a valid implementation of `getFlattened()` is to return an immutable collection:
https://github.com/protegeproject/protege/blob/6eb72cbf1244a25bc2b8fc0a672047a4d55a81c4/protege-editor-owl/src/main/java/org/protege/editor/owl/model/hierarchy/cls/InferredOWLClassHierarchyProvider.java#L85
