### ISSUE TITLE
Get explanations for inferred ObjectProperty. 

### ISSUE THREAD

**Issue by luispcosta** [protegeproject/protege#439]
Hello everyone.
First of all, this is not exactly an "issue" per se, I just don't know where to look for examples for what I'm trying to achieve. I posted the question on stackoverflow but I got no really useful answer, maybe 
someone here can help me.

Basically, I want to get the code that is being executed by protege when we click on "Get Explanations" for some inferred object property. Say that I run the reasoner on an ontology and the reasoner (I'm using Hermit) inferes a set of object properties for a specific individual. If I click on the "?" button near the inferred object property name, I can get the explanation of the reasoner for that inferred object property. Where can I find sample codes in the codebase on where this is being done?

I posted a more detailed question in this stack overflow question: http://stackoverflow.com/questions/37463589/get-inferred-object-property-assertions-hermit-reasoner

Sorry, I know this is not a proper "issue" of Protege itself, I just didn't know where else to ask and this seemed like a good idea to ask this. Feel free to close this issue and redirect me to some other place where I can ask and debate this question in more detail.

Thanks in advance!

**Comment by ykazakov** [comment]
Explanations in Protege are managed by the plugin called [Explanation Workbench](https://github.com/protegeproject/explanation-workbenchl). If you want to know what happens when you press "?", take a look at [JustificationBasedExplanationServiceImpl.java](https://github.com/protegeproject/explanation-workbench/blob/master/src/main/java/uk/ac/manchester/cs/owl/explanation/JustificationBasedExplanationServiceImpl.java). As you can see, it does not depend on the type of entailment that needs to be explained (object property axiom, class axiom, or any other type of axiom).

If you just want to compute sets of axioms in the explanations and are not interested in displaying them, you should probably look into [explanations in OWL API](https://github.com/matthewhorridge/owlexplanation).

**Comment by luispcosta** [comment]
Thanls @ykazakov . I will take a look into that! Maybe leave the issue if you think someone else might help here (maybe tag someone?), otherwise you can close it!

**Comment by matthewhorridge** [comment]
+1 for @ykazakov's answer.  I've nothing else to add so will close this.
