### ISSUE TITLE
Add an option to display vertical lines in the hierarchies for all look and feels

### ISSUE THREAD

**Issue by matthewhorridge** [protegeproject/protege#470]
Some of the look and feels in Protege display vertical lines in the class hierarchies, which can be useful if looking in large hierarchies.  These lines aren't displayed on the Mac look and feel.  Consider adding an option to show these.

**Comment by ykazakov** [comment]
Excellent! Works very well! Noticed just a few minor issues:
* Changing the flag "Show parent-child lines in trees" does not do anything. One needs to restart Protege. Perhaps add a warning similar to changing L&F?
* For the Protege L&F the lines become very subtle. Likely because a combination of the faint colour and dashed lines. Previously they were better visible.

**Comment by matthewhorridge** [comment]
> Changing the flag "Show parent-child lines in trees" does not do anything. One needs to restart Protege. Perhaps add a warning similar to changing L&F?

Yeah.  I initially added an interface that views could implement in order to get notified as to when they should repaint themselves.  In the end I didn't include this because I thought I would replace/overhaul event handling and use the Guava event bus.

> For the Protege L&F the lines become very subtle. Likely because a combination of the faint colour and dotted lines. Previously they were better visible.

Will look into this.  Reopening this issue.

**Comment by matthewhorridge** [comment]
Fixed this issue by preventing the line colour being set in the case of the Protege L&F.

**Comment by ykazakov** [comment]
That's much better, thanks!
