### ISSUE TITLE
Cannot reset preferences

### ISSUE THREAD

**Issue by tudorache** [protegeproject/protege#624]
Protege 5.2.0 (also present in Protege 5.1.0)

Steps to reproduce:
- Start a fresh installation of Protege 5.x.y
- Add the OWLViz tab
- Close Protege
- Start Protege
- File menu -> Preferences -> Reset preferences ...
- Close Protege
- Restart Protege

-> the OWLViz tab is still present, when it shouldn't have been.

Even after deleting:
- all Protege keys in ~/Library/Preferences/com.apple.java.util.prefs.plist; and
- all protege_preferences.xyz.plist in ~/Library/Preferences/
- edu.stanford.protege.plist in ~/Library/Preferences/

OWLViz tab is still visible.

Each time protege starts, it regenerates the file:
protege_preferences.application_preferences.tabs.plist in  ~/Library/Preferences/ that contains OWLViz.

**Comment by matthewhorridge** [comment]
Needs reproducing with Beta-5.5.0-8

**Comment by matthewhorridge** [comment]
With 5.5.0-beta-8:

When Protege closes normally the workspace is saved, so these steps don't work.  OWLViz will always be visible.  However, if I clear the preferences and then force Protege to quit (using Force Quit) rather than just closing normally, then OWLViz is no longer displayed as expected.
