### ISSUE TITLE
Shift key c triggers autocompletion instead of allowing the user to enter uppercase C

### ISSUE THREAD

**Issue by samsontu** [protegeproject/protege#637]
Protege 5.2
To reproduce:
1. Supposed we had entered "contains some WalkersShortbreadItem" as a class expression in the most recent operation somewhere
2. Now we want to specify that the individual is an instance Country
3. In the class expression dialog box, holding down shift key to type C triggers autocompletion for 'contains some WalkerShortbreadItem' instead of allowing a user to enter 'C'.

Perhaps autocompletion should be case-sensitive, since OWL is case-sensitive.

**Comment by csnyulas** [comment]
This may be a bigger issue. Another user (on a machine running Ubuntu) had problems entering a property chain expression in the property chain editor. Whenever he started entering the property name the auto-completion (or more specifically the history suggestion) automatically filled in the content of the field, and he was not able to enter the expression that he was trying write. Not even with copy paste did it work. Somehow the auto-completion overwrote what the user was trying to enter. Please feel free to create a separate issue for this if it turns out that it is a different problem.
