### ISSUE TITLE
SPARQL queries of go-plus.owl gene ontology

### ISSUE THREAD

**Issue by NatalieThurlby** [protegeproject/protege#697]
Hi, I'm trying to use Protege to do some research about tissue-specific gene expression.

I am having some difficulties doing SPARQL queries on the extended gene ontology. I have been able to write some successful queries using the example pizza ontology, but none using the extended gene ontology (at least not inside Protege). The following query works on [the ontobee website](http://www.ontobee.org/sparql) but not inside Protege:

```
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX obo-term: <http://purl.obolibrary.org/obo/>

SELECT DISTINCT ?x ?label

WHERE
{
?x rdfs:subClassOf obo-term:GO_0007610.
?x rdfs:label  ?label.
}
```

Can anyone please advise me as to why this might be?

**Comment by matthewhorridge** [comment]
Hi Natalie,
Which SPARQL UI are you using?  There are two in Protege and they offer different functionality.  What results do you get and what results do you expect?  I can execute your query in the Snap SPARQL plugin and I get some results.

**Comment by NatalieThurlby** [comment]
Hi Matthew,

Thank you for such a quick reply!

I'm using the "SPARQL query" and I don't get any results at all. I haven't
tried the "Snap" UI, so perhaps that's where I'm going wrong. I'll try this
when I'm next at my desktop. Could you explain why the Snap SPARQL query is
more suitable?

Best,

Natalie

**Comment by matthewhorridge** [comment]
Hi Natalie,

I only used Snap because that's what I had to hand.  Snap is a plugin for learning SPARQL-DL and SPARQL under the OWL entailment regime - in other words it takes inference into account.  It also (I think!) has a nicer UI with highlighting and autocompletion when compared to the other SPARQL plugin.  There are some queries that you cannot use it for though (structural queries involving the RDF/XML serialization of OWL) and it doesn't yet support the complete SPARQL 1.1 language, in particular property paths (it's not clear these make sense under the OWL entailment regime anyway) and a few other things like subqueries and some aggregation features.  In the end, it's best to try them both and see which one suits your needs.

**Comment by matthewhorridge** [comment]
@NatalieThurlby is it okay for me to close this issue?

**Comment by NatalieThurlby** [comment]
Yes that's fine

**Comment by matthewhorridge** [comment]
Thanks @NatalieThurlby
