### ISSUE TITLE
Protege adds an empty default prefix to the "Ontology Prefixes"

### ISSUE THREAD

**Issue by matthewhorridge** [protegeproject/protege#727]
See this image for an example:

![image001](https://user-images.githubusercontent.com/488607/32012779-e2bc00aa-b96d-11e7-9b13-f6fbd792be56.png)

**Comment by matthewhorridge** [comment]
After a bit of digging it turns out that it's the OWL API that does this.  The only way to override this is to... set a default (empty) prefix.  Changing this so that it ends in a /

**Comment by matthewhorridge** [comment]
Default prefix set to ontology IRI plus slash.  This is now updated if the ontology IRI changes.

**Comment by csnyulas** [comment]
Shouldn't the end of the default prefix be set to whatever the separator is selected in the New Entity configuration? Otherwise if someone uses `#` as their separator for generating the IRIs of new entities, and decide to render by entity IRI short name (Id) or prefixed name, they will get the full IRI displayed instead of just the short name.

**Comment by matthewhorridge** [comment]
I wondered about this when I did the implementation, but I decided against it.  If there's a desire for a prefix ending in a fragment then this can be manually edited and it won't be overwritten.  (The default is to '/' as an ending for a prefix in other places)
