### ISSUE TITLE
Display all language tags in dropdown menu

### ISSUE THREAD

**Issue by rsgoncalves** [protegeproject/protege#784]
Protege should show all the standard language tags in the annotation property assertion dropdown menu.

**Comment by csnyulas** [comment]
Or alternatively, at least all the ones that were used in the current ontology.

**Comment by rsgoncalves** [comment]
Potentially that could be an option, since it wouldn't work for a new ontology.

**Comment by csnyulas** [comment]
True that with a new ontology the user would need to know about what language tags exist (which I assume most users probably know, at least for their own country/language). However, listing all the valid language tags (and there are 190 of two letter language tags, and way more if you count the three letter language tags and/or the country/script specific ones, see [IANA subtag lang. registry](https://www.iana.org/assignments/language-subtag-registry/language-subtag-registry) and [lang. tag specification](https://www.w3.org/International/articles/language-tags/)) would be probably too much. 

Maybe the previously used language tags could be saved in the Protege properties, so that the user can see all relevant languages (based on his or her prior ontology editing activity), even in a new ontology. This list could be initialized with the OS language preference on the first start of a freshly installed Protege.

**Comment by rsgoncalves** [comment]
Rather than a dropdown, perhaps this should be a search field that allows looking up language tags in the IANA registry according to their tag or description.

**Comment by matthewhorridge** [comment]
Implemented as a drop down with an overriding editor
