### ISSUE TITLE
Upgrade OWL API to 4.5.5

### ISSUE THREAD

**Issue by matthewhorridge** [protegeproject/protege#799]
Upgrading to OWL API 4.5.5 is problematic due class loading problems that occur with the combination of OSGi and the custom OWL API Dependency Injection Mechanism.

More comments here:  https://github.com/protegeproject/protege/pull/798

While we can workaround this in Protege by using manual DI (or some other framework) it's causing problems with any plugins (e.g. reasoners) that instantiate their own OWLOntologyManager using OWLManager.create.....  This is exhibited in HermiT for example.

Copying in @ignazio1977, @cmungall, @jamesaoverton

**Comment by matthewhorridge** [comment]
Above problems not exhibited with ELK, FaCT++ or Pellet

**Comment by matthewhorridge** [comment]
Problem occurs with Mastro DL-Lite reasoner

**Comment by matthewhorridge** [comment]
Relevant error message is: 

"No files found for META-INF/services/org.semanticweb.owlapi.model.OWLOntologyManager"

**Comment by matthewhorridge** [comment]
Explanation is broken

**Comment by matthewhorridge** [comment]
Also relevant stack trace
```java
java.lang.NullPointerException
  at org.semanticweb.owlapi.utilities.Injector.inject(Injector.java:186)
  at org.semanticweb.owlapi.apibinding.OWLManager.createOWLOntologyManager(OWLManager.java:106)
```

**Comment by matthewhorridge** [comment]
Looking at this code here:

```java
protected ClassLoader classLoader() {
        ClassLoader loader = Thread.currentThread().getContextClassLoader();
        if (loader == null) {
            // in OSGi, the context class loader is likely null.
            // This would trigger the use of the system class loader, which would
            // not see the OWLAPI jar, nor any other jar containing implementations.
            // In that case, use this class classloader to load, at a minimum, the
            // services provided by the OWLAPI jar itself.
            loader = getClass().getClassLoader();
        }
        return loader;
    }
```

The context class loader is not null.  It's an instance of ```sun.misc.Launcher$AppClassLoader```.  The files that are being searched for using this class loader are never found ```"No files found for META-INF/services/org.semanticweb.owlapi.model.OWLOntologyManager"```

**Comment by ignazio1977** [comment]
Looks like one of the resources did not make it to the OSGi jar. Might be due to an error setting up the shade plugin.

**Comment by ignazio1977** [comment]
It's not a matter of shading in the OWLAPI build, the file is where it's supposed to be.

The same folder contains other files that were already in use before the DI change - i.e., the parser factory list - so I'm assuming the managers being created were not able to parse ontologies. I'm going to take a look at what HermiT is doing with creating managers.

OWLExplanation is creating managers to allow creation of ontologies - I was planning a change to allow to remove the dependency on OWLManager, so that an OWLOntologyManager provider could be injected instead (in the context of allowing the OWLExplanation library to be included in the OWLAPI dependencies without circular dependencies on apibinding). The change is small, so might be worth including in your current version.

**Comment by ignazio1977** [comment]
Yes the very same. Not sure why - I guess I was embedding that jar earlier.

**Comment by matthewhorridge** [comment]
okay but it should still be on the class path because it's in the class path of a bundle available at runtime in Protege.

**Comment by ignazio1977** [comment]
True. I just noticed the dependency that used to be included is a repackaging under a different artifact name, which might break the import directives for the OSGi packager. Now that the api package depends on plain javax.inject, without guice involved, it might be that a different dependency is needed.

**Comment by ignazio1977** [comment]
I've got Protege booting without error when the plain javax.inject jar (not the OSGi wrapped one) is embedded in owlapi-osgidistribution.

I'll check the contents of the OSGi wrapped jar and see if the problem is in some package inclusion.

I've tried HermiT 1.4.0.432 but it fails because it cannot get a new enough guava version - that's a Hermit distribution specific issue (it relies on a version of OWLAPI that has unnecessarily high requirements). I'll sort that separately.

**Comment by ignazio1977** [comment]
Yep, problem was in the Import-Package section. I'll get a snapshot on Sonatype.

**Comment by ignazio1977** [comment]
Snapshot on Sonatype for you to try: https://oss.sonatype.org/content/repositories/snapshots/net/sourceforge/owlapi/owlapi-osgidistribution/4.5.6-SNAPSHOT/

**Comment by matthewhorridge** [comment]
.... and the "Injecting values ...." logging

**Comment by ignazio1977** [comment]
Currently info level, I'll move to debug.

**Comment by matthewhorridge** [comment]
Thanks!!

**Comment by ignazio1977** [comment]
OWLAPI 4.5.6 and HermiT 1.4.0.456 have been released.

**Comment by matthewhorridge** [comment]
Great.  Thanks so much.
