### ISSUE TITLE
Remove prefix button has no tooltip

### ISSUE THREAD

**Issue by wouterbeek** [protegeproject/protege#897]
There are 3 buttons in the “Ontology Prefixes” tab.  2 of them have a tooltip but one of them does not (the on the right-hand side).  This button seems to remove prefix declarations.  It would be nice/consistent if this button would also have a tooltip.

**Comment by ykazakov** [comment]
@matthewhorridge could you, please, comment why MList now needs a hardcoded DefaultListModel? Particularly, the added list selection listener should not do anything:

```
addListSelectionListener(e -> {
     model.set(e.getFirstIndex(), model.getElementAt(e.getFirstIndex()));
});
```

Is it to fire re-rendering, or why is it needed?

The reason why I am asking is that the [proof explanation plugin](https://github.com/liveontologies/protege-proof-explanation) of ELK uses MList to display proof-based explanation. It uses a custom list model to dynamically change the displayed axioms when the proof is expanded. Now this plugin breaks because the initialised DefaultListModel always remains empty. 
I am trying to find a workaround.

**Comment by matthewhorridge** [comment]
@ykazakov I have no idea... or why this got in there!  Looks like a mistake.  Let me see if this can be reverted.

**Comment by ykazakov** [comment]
I have commented out this listener and did not notice anything strange so far.
The listener would make sense if when selecting an element of a list, a layout needs to be recomputed, i.e., some cell sizes change. Can something like this happen? I do not think this can be caused by tooltips.
